apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberay-service-account
  namespace: kube-ray  # Specify the namespace if different from default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberay-service-account-binding
subjects:
- kind: ServiceAccount
  name: kuberay-service-account
  namespace: kube-ray  # Ensure this matches the namespace where the ServiceAccount was created
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
