apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: example.com/nfs
mountOptions:
  - vers=4.1
parameters:
  server: 192.168.209.37
  path: /srv/nfs/kube-ray
reclaimPolicy: Retain
