apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: kube-ray
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ]
      volumeMounts:
        - mountPath: "/mnt/nfs"
          name: nfs-volume
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
